### ISSUE TITLE
Dockerfile: FROM image is not pinned

### ISSUE THREAD

**Issue by buxx** [tracim/docker_tracim#10]
The FROm clause is actually `FROM debian:latest`. I think it can be problematic when next debian release will be effective: Our image certainly break.

I think we should pin it at `FROM debian:9`: ensure last debian 9 version, and permit manually switch to debian 10.

**Comment by buxx** [comment]
Done.

**Comment by lebouquetin** [comment]
Actually, this bug is at the origin of #8 : the user was working with debian:latest which was in old version (ie 8 instead of 9)
