### ISSUE TITLE
Use apache frontend to reduce radicale/webdav route problems

### ISSUE THREAD

**Issue by buxx** [tracim/docker_tracim#12]
When tracim serve html files to client, it's hard to servce radicale/webdav correct url: wich address of container/host ?

So: Configure apache frontend to use unique entrypoint ? Like 192.168.1.111:80, 192.168.1.111/radicale:80, 192.168.1.111/webdav:80

**Comment by tracim** [comment]
If its necessary also for tracim v2, please create issue in tracim repo.
I close this issue.
