### ISSUE TITLE
optimiser l'image Docker/ réduire la taille

### ISSUE THREAD

**Issue by k3ck3c** [tracim/docker_tracim#9]
Quand je regarde le Dockerfile, 
https://github.com/tracim/docker_tracim/blob/master/Debian_Uwsgi/Dockerfile

il n'est pas conforme à
https://www.dajobe.org/blog/2015/04/18/making-debian-docker-images-smaller/

L'image doit pouvoir être réduite en faisant de cette manière.

**Comment by buxx** [comment]
Bonjour,
On va regarder de près cet article, merci pour l'information.
Bux.

**Comment by tracim** [comment]
If its necessary also for tracim v2, please create issue in tracim repo.
I close this issue.
